name: Build and Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build and push Homebrew formula

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Set up variables
        id: vars
        run: |
          VERSION=${GITHUB_REF##*/}
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Package release tarball
        run: |
          mkdir release
          cp -r bin src bb.edn README.md release/
          tar -czf worktree-manager.tar.gz -C release .

      - name: Calculate SHA256
        id: shasum
        run: |
          SHA=$(shasum -a 256 worktree-manager.tar.gz | awk '{print $1}')
          echo "sha256=$SHA" >> "$GITHUB_OUTPUT"

      - name: Upload tarball to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: worktree-manager.tar.gz

      - name: Clone homebrew tap repo
        uses: actions/checkout@v4
        with:
          repository: bolivier/homebrew-worktree-manager
          token: ${{ secrets.HOMEBREW_CI_TOKEN_PAT }}
          path: homebrew-tap

      - name: Replace placeholders in formula
        run: |
          TEMPLATE_PATH="homebrew-tap/Formula/worktree-manager.template.rb"
          OUTPUT_PATH="homebrew-tap/Formula/worktree-manager.rb"

          VERSION="${{ steps.vars.outputs.version }}"
          SHA="${{ steps.shasum.outputs.sha256 }}"

          sed "s|__VERSION__|$VERSION|g; s|__SHA__|$SHA|g" "$TEMPLATE_PATH" > "$OUTPUT_PATH"

      - name: Commit and push updated formula
        run: |
          cd homebrew-tap
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          BRANCH="update-formula-${{ steps.vars.outputs.version }}"
          git checkout -b "$BRANCH"
          git add Formula/worktree-manager.rb
          git commit -m "Update formula for version ${{ steps.vars.outputs.version }}"
          git push origin "$BRANCH"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.HOMEBREW_CI_TOKEN_PAT }}
          path: homebrew-tap
          branch: "update-formula-${{ steps.vars.outputs.version }}"
          base: main
          title: "Update worktree-manager formula to ${{ steps.vars.outputs.version }}"
          body: |
            Automated PR to update the formula for version `${{ steps.vars.outputs.version }}`.
            SHA256: `${{ steps.shasum.outputs.sha256 }}`
