name: Build Release

on:
  release:
    types: [published]

jobs:
  build-and-release:
    name: Package release tarball
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create release tarball
        run: |
          mkdir release
          cp -r bin src bb.edn README.md LICENSE release/
          tar -czf worktree-manager.tar.gz -C release .

      - name: Calculate SHA256
        id: shasum
        run: |
          SHA=$(shasum -a 256 worktree-manager.tar.gz | awk '{print $1}')
          echo "sha256=$SHA" >> "$GITHUB_OUTPUT"

      - name: Upload tarball to release
        uses: softprops/action-gh-release@v2
        with:
          files: worktree-manager.tar.gz

      - name: Update Homebrew formula in tap
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.HOMEBREW_CI_TOKEN_PAT }}
          commit-message: "Update formula to version ${{ github.event.release.tag_name }}"
          title: "Update formula to ${{ github.event.release.tag_name }}"
          body: "Auto-generated by CI from release"
          branch: "update-formula-${{ github.event.release.tag_name }}"
          base: "main"
          path: ../homebrew-worktree-manager
          add-paths: Formula/worktree-manager.rb
        env:
          FORMULA_SHA: ${{ steps.shasum.outputs.sha256 }}
          FORMULA_VERSION: ${{ github.event.release.tag_name }}
