name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Install babashka
        run: bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)

      - name: Run tests
        run: bb test
